postgres:
  dsn: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable&search_path=orchestrator_service"
  max_conns: 25
  min_conns: 5
  conn_max_idle: 1800s
  health_check_int: 60s

rabbitmq:
  url: "amqp://admin:admin@localhost:5672/"
  reconnect_attempts: 2
  reconnect_delay: 30s
  prefetch_count: 0
