auth:
  jwt_secret_key: "my_super_scret_key"
  jwt_ttl: 24h
http:
  addr: localhost:8080
grpc:
  addr: localhost:9001
rabbitmq:
  url: "amqp://admin:admin@localhost:5672/"
  reconnect_attempts: 2
  reconnect_delay: 30s
  prefetch_count: 0
postgres:
  dsn: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
  min_conns: 0
  max_conns: 5
  conn_max_idle: 1m
  health_check_int: 1m
grpc_client:
  categories:
    target: "localhost:9002"